config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :coins

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    puts coin_params

    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Moeda cadastrada com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Moeda editada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda deletada com sucesso" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def data_br(data_us)
      data_us.strftime("%d/%m/%Y")
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Descrição %>
    <%= form.text_field :description, :required =>true %>
  </div>

  <div class="field">
    <%= form.label :Sigla %>
    <%= form.text_field :acronym, :required =>true %>
  </div>

  <div class="field">
    <%= form.label :Ícone %>
    <%= form.text_field :url_image, :required =>true %>
  </div>

  <div class="actions">
    <%= form.submit texto_da_acao %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editando Moeda</h1>

<%= render partial: "form", locals: {texto_da_acao: 'Atualizar', coin:@coin} %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moedas</h1>

<table>
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><% if coin.url_image %>
              <%=    image_tag coin.url_image, size: "45x45" %>
                <% else %>
              <%=    image_tag "https://imagensemoldes.com.br/wp-content/uploads/2021/02/Imagem-Letra-X-PNG.png", size: "45x45" %>
                <% end %>
                 </td>
        <td><%= link_to 'Mostrar', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Apagar', coin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar nova moeda', new_coin_path %>

app/views/coins/new.html.erb
<strong><h1>Nova Moeda</h1></strong>

<%= render partial: "form", locals: {texto_da_acao: 'Criar', coin: @coin} %>

<%= link_to 'Voltar', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Sígla:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Imagem:</strong>
  <% if @coin.url_image %>
        <%= image_tag @coin.url_image, size: "30x30" %>
      <% else %>
        <%=image_tag "https://imagensemoldes.com.br/wp-content/uploads/2021/02/Imagem-Letra-X-PNG.png", size: "45x45" %>
    <% end %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/_menu.html.erb
<ul>
  <li>
    <a href="/coins"> Cadastrar Coins </a>
  </li>
</ul>

app/views/welcome/index.html.erb
<h1>Seja Bem-Vindo</h1>


<p><strong>Data:</strong> <%= data_br(Date.today) %></p>


<%= render "menu" %>